config/urls.py
from django.conf import settings
from django.contrib import admin
from explorea.events import views
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = 	[
	path('', views.index, name='index'),
	path('events/', include('explorea.events.urls', namespace='events')),
    path('accounts/', include('explorea.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('cart/', include('explorea.cart.urls', namespace='cart')),
				]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explorea/accounts/urls.py
from . import views
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
										password_reset,
										password_reset_done,
										password_reset_confirm,
										password_reset_complete
										)

app_name = 'accounts'

urlpatterns = 	[
	path('login/', auth_views.login,{'template_name': 'accounts/login.html'}, name='login'),
	path('logout/', auth_views.logout,{'template_name': 'accounts/logged_out.html'}, name='logout'),
	path('register/', views.register, name='register'),
	path('profile/', views.profile, name='profile'),

	path('hosts/', views.host_list, name='host_list'),
	path('become-host/', views.become_host, name='become_host'),
	path('host/profile/<username>/', views.host_profile, name='host_profile'),

	path('profile/edit/', views.edit_profile, name='edit_profile'),
	path('change-password/', views.change_password, name='change_password'),
	path('reset_password/complete', password_reset_complete, name='password_reset_complete'),
	path('reset-password/done/', password_reset_done, name='password_reset_done'),
	path('reset-password/', password_reset,{'template_name': 'accounts/reset_password.html',
		'post_reset_redirect': 'password_reset_done',
		'email_template_name': 'accounts/reset_password_email.html'},
		name='reset_password'),

	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm,
		{'post_reset_redirect': 'password_reset_complete'}, name='password_reset_confirm'),
	url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.activate_host, 
		name='activate_host'),
				]

explorea/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='detail'),
    # Another possible paths ...,

				
				]

explorea/events/urls.py
from . import views
from django.urls import path

app_name = 'events'

urlpatterns = [
    path('new/', views.CreateEventView.as_view(), name='create_event'),
    path('my_events/', views.MyEventsView.as_view(), name='my_events'),
    path('search/', views.EventSearchView.as_view(), name='search'),
    
    path('detail/<slug:slug>/', views.EventDetailView.as_view(), name='event_detail'),
    path('update/<slug:slug>/', views.UpdateEventView.as_view(), name='update_event'),
    path('delete/<slug:slug>/', views.DeleteEventView.as_view(), name='delete_event'),
    
    path('<int:event_id>/new_run/', views.create_event_run, name='create_event_run'),
    path('update_run/<int:event_run_id>/', views.update_event_run,name='update_event_run'),
    path('delete_run/<int:event_run_id>/', views.delete_event_run,name='delete_event_run'),

    path('<category>/', views.EventListView.as_view(), name='events'),
                ]

explorea/accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


def image_dir(instance, filename):
    return 'user_{}/profile_{}'.format(instance.user.id, filename)


class Profile(models.Model):
    user 	= models.OneToOneField(settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, primary_key=True)
    is_host = models.BooleanField(default=False)
    about 	= models.TextField(max_length=500)
    avatar 	= models.ImageField('Upload your photo', 
        upload_to=image_dir, null=True)


def get_absolute_url(self):
        return reverse('accounts:host_profile', args=[self.user.username])

explorea/cart/models.py
from django.db import models

# Create your models here.

explorea/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from core.validators import validate_human_name
from .models import Profile

# global variable
UserModel = get_user_model()


class RegisterForm(UserCreationForm):
	first_name	= forms.CharField(max_length=100, validators=[validate_human_name,])
	last_name	= forms.CharField(max_length=100, validators=[validate_human_name,])

	class Meta:
		model = UserModel
		fields = [
			'username',
			'email',
			'first_name',
			'last_name',
			'password1',
			'password2',
					]

class EditUserForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    
    class Meta:
        model = UserModel
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        		]

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['about', 'avatar']


									

explorea/accounts/views.py
# imports lower are important in the "become_host" view 
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import PasswordResetTokenGenerator
# aaa
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
# a
from .models import Profile
# b
from .forms import RegisterForm, EditProfileForm, EditUserForm


token_generator = PasswordResetTokenGenerator()
UserModel = get_user_model()


@login_required
def profile(request):
	''' This function render only basic information about the user's account '''
	return render(request, 'accounts/profile.html')


def register(request):
	''' The register function. '''
	if request.method == 'POST':
		# Create thte form and populate it with data from the POST request
		form = RegisterForm(request.POST)

		# Validate the data in the form
		if form.is_valid():
			user = form.save()
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=user.username, password=raw_password)
			login(request, user)
			return redirect('profile')
	# if the request method is GET type
	form = RegisterForm()
	return render(request, 'accounts/register.html', {'form': form})


@login_required
def edit_profile(request):
	''' we want to edit our profile section '''
	UserForm = EditUserForm(request.POST or None, instance=request.user)
	ProfileForm = EditProfileForm(request.POST or None, request.FILES or None,
		instance=request.user.profile)

	if request.method == 'POST':
		if UserForm.is_valid() and ProfileForm.is_valid():
			user = UserForm.save()
			profile = ProfileForm.save()

			return redirect('accounts:profile')
	return render(request, 'accounts/edit_profile.html',
		{'UserForm': UserForm, 'ProfileForm': ProfileForm})


@login_required
def change_password(request):
	''' The user wants to change his current password'''

	if not request.user.is_authenticated:
		return redirect('login')

	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)
		
		if form.is_valid():
			user = form.save()
			# we need to obtain a new session hash due to new password
			update_session_auth_hash(request, user)
			return redirect('accounts/profile/')
		else:
			return render(request, 'accounts/change_password.html', {'form': form})
	
	# GET method
	else:
		form = PasswordChangeForm(user=request.user)
		return render(request, 'accounts/change_password.html', {'form': form})


@login_required
def host_list(request):
	''' This view is accessible only to those registerred at our site.'''
	profiles = Profile.objects.filter(is_host=True)
	if request.user.profile.is_host:
		profiles = profiles.exclude(user__pk=request.user.id)

	return render(request, 'accounts/host_list.html', {'profiles':profiles})


@login_required
def become_host(request):
	''' aaa '''
	verificationEmailTemplate = 'accounts/hostVerificationEmail.html'
	emailContext = {
		'user': request.user,
		'domain': get_current_site(request).domain,
		'uidb64': urlsafe_base64_encode(force_bytes(request.user.pk)).decode(),
		'token': token_generator.make_token(request.user)
					}
	html_body 	= render_to_string(verificationEmailTemplate, emailContext)
	subject 	= 'Explorea Host Verification'
	from_email 	= 'admin@explorea.com'
	to_email 	= request.user.email
	email 		= EmailMessage(subject, html_body, from_email, [to_email])
	email.send()

	return render(request, 'accounts/verificationSent.html')


def activate_host(request, uidb64, token):
	'''We want to render html correctly with proper urls.'''
	try:
		uid 	= urlsafe_base64_decode(uidb64).decode()
		user 	= UserModel._default_manager.get(pk=uid)
	except (TypeError, ValueError, OverflowError, User.DoesNotExist):
		user 	= None

	if user is not None and token_generator.check_token(user, token):
		user.profile.is_host = True
		user.profile.save()
		return render(request, 'accounts/verificationComplete.html')
	else:
		return render(request, 'accounts/invalidLink.html')


@login_required
def host_profile(request, username):
    host = UserModel.objects.get(username=username)
    return render(request, 'accounts/hostProfile.html', {'host': host})

explorea/cart/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Our first view for testing purposes
# ...
class CartDetailView(TemplateView):
    template_name = "cart/cart_detail.html"

explorea/events/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Event, EventRun, Album, Image

from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, FormMixin
from django.views.generic.edit import DeleteView, CreateView, UpdateView

from .forms import EventForm, EventRunForm, EventFilterForm, EventSearchFilterForm


def index(request):
    ''' Main page, kind of welcome page with usefull text'''
    return render(request, 'events/index.html')


class GetFormMixin(FormMixin):

	def get_form_kwargs(self):
		kwargs = {
			'initial': self.get_initial(),
			'prefix': self.get_prefix(),
			'data': self.request.GET,
			}
		return kwargs
		

class EventListView(GetFormMixin, ListView):
    model 				= EventRun
    context_object_name = 'EventRuns'
    form_class 			= EventFilterForm
    template_name 		= 'events/event_listing.html'
    paginate_by 		= 4

    def get(self, request, *args, **kwargs):
    	self.form = self.get_form()
    	if self.form.is_valid():
    		return super().get(request, *args, **kwargs)
    	self.object_list = []
    	return self.form_invalid(self.form)

    def get_queryset(self):
        qs = self.model._default_manager.all().filter_by_category(self.kwargs['category'])
        return qs.FirstFilter(**self.form.cleaned_data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['FilterForm'] = self.form
        return context


class EventDetailView(DetailView):
	model 				= Event
	template_name 		= 'events/event_detail.html'
	context_object_name = 'event'

	def get_context_data(self, **kwargs):
		'''Insert the single object into the context dictionary.'''
		context = super().get_context_data(**kwargs)
		context['runs'] = self.object.ActiveRuns()
		return context


class CreateEventView(LoginRequiredMixin, CreateView):
	model 			= Event
	form_class 		= EventForm
	template_name 	= 'events/create_event.html'

	def form_valid(self, form):
		form.cleaned_data.pop('gallery')
		event = Event.objects.create(host=self.request.user, **form.cleaned_data)

		# save the individual images
		for file in self.request.FILES.getlist('gallery'):
			Image.objects.create(album=event.album, image=file, title=file.name)

		return redirect(event.get_absolute_url())


@login_required
def update_event(request, slug):
	'''New view of our update.html. It relates with create_event.view'''
	event = Event.objects.get(slug=slug)
	EvntForm = EventForm(request.POST or None, request.FILES or None, instance=event)
	FileForm = MultipleFileForm(files=request.FILES or None)

	if request.method == 'POST':
		if EvntForm.is_valid() and FileForm.is_valid():
			event = EvntForm.save()
			for file in request.FILES.getlist('gallery'):
				Image.objects.create(album=event.album, image=file, title=file.name)

			return redirect(event.get_absolute_url())
	return render(request, 'events/create_event.html', 
		{'EvntForm': EvntForm, 'FileForm': FileForm, 'event': event})


class UpdateEventView(LoginRequiredMixin, UpdateView):
	model 			= Event
	form_class 		= EventForm
	template_name 	= 'events/create_event.html'

	def form_valid(self, form):
		event = form.save()

		# save the individual images
		for file in self.request.FILES.getlist('gallery'):
			Image.objects.create(album=event.album, image=file, title=file.name)

		return redirect(event.get_absolute_url())


class MyEventsView(LoginRequiredMixin, ListView):
	# attributes
	context_object_name = 'events'
	template_name 		= 'events/my_events.html'

	def get_queryset(self):
		''' This method gets the data from database.'''
		return Event.objects.filter(host_id=self.request.user.id)


@login_required
def create_event_run(request, event_id):
	''' In case we want to add a new event run.'''
	if request.method == 'POST':
		form = EventRunForm(request.POST)

		if form.is_valid():
			event_run 		= form.save(commit=False)
			event_run.event = Event.objects.get(pk=event_id)
			event_run.save()

			url = 'events/detail/{}'.format(event_id)
			return redirect(url)
	return render(request, 'events/create_event_run.html', {'form': EventRunForm()})


@login_required
def delete_event(request, slug):
	''' We want to terminate an event '''
	Event.objects.get(slug=slug).delete()
	return redirect('my_events')


class DeleteEventView(LoginRequiredMixin, DeleteView):
	model 		= Event
	success_url = reverse_lazy('events:my_events')


# @login_required
# def create_event_run(request, event_id):
# 	if request.method == 'POST':
# 		form = EventRunForm(request.POST)

# 		if form.is_valid():
# 			event_run = form.save(commit=False)
# 			event_run.event = Event.objects.get(pk=event_id)
# 			event_run.save()

# 			url = '/events/detail/{}'.format(event_id)
# 			return redirect(url)

# 	args = {'form': EventRunForm()}
# 	return render(request, 'events/create_event_run.html', args)

@login_required
def create_event_run(request, event_id):
	if request.method == 'POST':
		form = EventRunForm(request.POST)

		if form.is_valid():
			event_run = form.save(commit=False)
			event_run.event = Event.objects.get(pk=event_id)
			event_run.save()
			messages.success(request, 'The run has been created successfully')
			return redirect(event_run.event.get_absolute_url())
		
		else:
			messages.error(request, 'The run could not be created')

	args = {'form': EventRunForm()}
	return render(request, 'events/create_event_run.html', args)


@login_required
def update_event_run(request, event_run_id):
	event_run = EventRun.objects.get(pk=event_run_id)
	if request.method == 'POST':
		form = EventRunForm(request.POST, instance=event_run)

		if form.is_valid():
			event_run = form.save()
			event_id  = event_run.event.id
			url  	  = '/events/detail/{}'.format(event_id)
			return redirect(url)

	return render(request, 'events/update_event_run.html',
		{'form': EventRunForm(instance=event_run)})


@login_required
def delete_event_run(request, event_run_id):
	run = EventRun.objects.get(pk=event_run_id)
	event_id = run.event.id
	run.delete()

	url = '/events/detail/{}'.format(event_id)
	return redirect(url)


class EventSearchView(ListView):
	'''This class-based view works with searchbar in header'''
	model 				= EventRun
	form_class 			= EventSearchFilterForm
	template_name 		= 'events/event_listing.html'
	paginate_by 		= 4
	context_object_name = 'EventRuns'
	#extra_context 		= {'FilterForm': EventFilterForm()}

	def get(self, request, *args, **kwargs):
		self.form = self.get_form()
		if self.form.is_valid():
			self.query = self.form.cleaned_data.pop('q')
			return super().get(request, *args, **kwargs)

		self.object_list = []
		return self.form_invalid(self.form)

	def get_queryset(self):
		qs =  self.model._default_manager.search(self.query)
		return qs.FirstFilter(**self.form.cleaned_data)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['FilterForm'] = self.form
		return context

explorea/templates/accounts/change_password.html
{% extends 'base.html' %}
<html>
<head>
	{% block title %}
	<title>Password change</title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<div class="container">
		<br>
		<h2>Change password</h2>
		<form method='POST'>
		{% csrf_token %}
		{% for field in form.visible_fields %}
			{% for error in field.errors %}
			{{ error }}
			{% endfor %}
			<p>{{ field.label_tag }}{{ field }}</p>
		{% endfor %}
		<!-- <input type="submit" value="Change"> -->
		<button type="submit" class="btn btn-outline-danger">Change</button>
		</form>
	</div>
	{% endblock content %}
</body>
</html>

explorea/templates/accounts/edit_profile.html
{% extends 'base.html' %}
<html>
<head>
	{% block title %}
	<title>Edit Profile</title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<div>
		<h2>Edit profile</h2>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
    			{% for field in UserForm.visible_fields %}
        			{% for error in field.errors %}
        			{{ error }}
        			{% endfor %}

			        {% if field.label != 'Password' %}
			        <p>{{ field.label_tag}}{{ field }}</p>
			        {% endif %}
        

    			{% endfor %}

			    {% for field in ProfileForm.visible_fields %}
			        {% for error in field.errors %}
			        {{ error }}
			        {% endfor %}
			        <p>{{ field.label_tag}}{{ field }}</p>

			    {% endfor %}
			    <button type="submit">Save</button>
			</form>
		</div>
{% endblock content %}
</body>
</html>

explorea/templates/accounts/hostProfile.html
{% extends 'base.html' %}
{% load static %}
{% load account_tags %}

{% block content %}

<br>
<table>
    <tr>
        <td>
        {% if  host.profile.avatar|has:'url' %}
            <img src="{{ host.profile.avatar.url }}">
        {% else %}
            <img src="{% static 'img/avatar.png' %}">
        {% endif %}
        </td>
    </tr>
    <tr><td>hostname: </td><td>{{ host.hostname }}</td></tr>
    <tr><td>First Name: </td><td>{{ host.first_name }}</td></tr>
    <tr><td>Last Name: </td><td>{{ host.last_name }}</td></tr>
    <tr><td>Email: </td><td>{{ host.email }}</td></tr>
    <tr><td>Joined: </td><td>{{ host.date_joined }}</td></tr>
    <tr><td>About Me: </td><td>{{ host.profile.about }}</td></tr>
</table>
{% endblock content %}

explorea/templates/accounts/hostVerificationEmail.html
<p>Dear {{ user.username }}</p>

<p>Hello,</p>

<p>you are one step from becoming host at Explorea.</p>
<p>Please click the below link button to complete the verification:</p>
<a href="http://{{ domain }}{% url 'accounts:activate_host' uidb64 token %}" target="_blank">Verify</a>

<p>Thanks for using our site!</p>
<p>The Explorea team</p>

explorea/templates/accounts/invalidLink.html
{% extends 'base.html' %}
<head>
	{% block title %}
	<title>Link invalid</title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<p>Sadly your verification has gone wrong. Maybe its your link older then one week?</p>
	<p><a href="{% url 'accounts:become_host' %}">Apply again</a></p>
	{% endblock content %}
</body>

explorea/templates/accounts/logged_out.html
{% extends 'base.html' %}
<html>
<head>
	{% block title %}
	<title>Logged out</title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<div class="container">
		<br>
		<h2>Goodbye</h2>
		<p>You have been logged out. But if you decide to log in again, 
		we will be happy to see you here.</p>
	</div>
	{% endblock content %}
</body>
</html>

explorea/templates/accounts/login.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
{% block title %}
<title>Login</title>
{% endblock title %}
</head>
<body>
	{% block content %}	
	<div class="Container">
		<div class="LogPicture">
		</div>
		<div class="LogWindow">
			<form method='Post'>
				<h2>Login</h2>
				{% csrf_token %}
				<p>{{ form.as_p }}</p>
				<button type="submit">Login</button>
				<a class="ForgottingPassword" href="{% url 'accounts:reset_password' %}">Forget password?</a>
			</form>
		</div>
	</div>
	{% endblock content %}
</body>
</html>

explorea/templates/accounts/page.html
<!DOCTYPE html>
<html>
<head>
    <title>Connecting CSS with HTML</title>
    <link rel="stylesheet" type="text/css" href="styles.css">

</head>
<body>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</body>
</html>

explorea/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load account_tags %}
<html>
<head>
	{% block head %}
	<title>Profile</title>
	{% endblock head %}
</head>
<body>
	{% block content %}
	<br>
	<table>
    	<tr>
       		<td>
        	{% if  user.profile.avatar|has:'url' %}
            	<img src="{{ user.profile.avatar.url }}">
       		{% else %}
            	<img src="{% static 'img/avatar.png' %}">
        	{% endif %}
        	</td>
        </tr>
    </table>
	<h2> My profile </h2>
	<br>
	<p>Username: {{ user }}</p>
	<p>First name: {{ user.first_name}}</p>
	<p>Last name: {{ user.last_name}}</p>
	<p>Email: {{ user.email }}</p>
	<br>
	<button type="submit" href="{% url 'accounts:edit_profile' %}">Edit profile</button>
	{% endblock content %}
</body>
</html>

explorea/templates/accounts/register.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
{% block title %}
<title>Register</title>
{% endblock title %}
</head>
<body>
	{% block content %}
	<div class="Container">
		<div class="LogPicture">
		</div>
		<div class="RegWindow">
			<form method='Post'>
				<h2>Create account</h2>
				{% csrf_token %}
				{% for field in form.visible_fields %}
					{% for error in field.errors %}
					{{ error }}
					{% endfor %}
					<p>{{ field.label_tag }}{{ field }}</p>
				{% endfor %}
				<button type="submit">Submit</button>
			</form>
		</div>
	</div>
	{% endblock content%}
</body>
</html>

explorea/templates/accounts/reset_password.html
{% extends 'base.html' %}
<html>
<head>
	{% block title %}
	<title>Password reset</title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<div class="container">
		<br>
		<h2>Reset password</h2>
		<p>Enter your email below and click "Submit". We will send you the reset link to your email immediately.</p>
		<form method='post'>
		{% csrf_token %}
		{% for field in form.visible_fields %}
			{% for error in field.errors %}
			{{ error }}
			{% endfor %}
			<p>{{ field.label_tag }}{{ field }}</p>
		{% endfor %}
		<button type="submit" class="btn btn-outline-danger">Save</button>
		</form>
	</div>
	{% endblock content %}
</body>
</html>

explorea/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Tento email jste obdrzeli, protoze jste zadali o resetovani hesla pro vas uzivatelsky ucet na {{ site_name }}.{% endblocktrans %}

{% trans "Prosim prejdete na nasledujici stranku a vyberte nove heslo:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Vase uzivatelske jmeno, jen pro pripad, kdybyste zapomneli:" %} {{ user.get_username }}

{% trans "Dekujeme, ze pouzivate nase stranky!" %}

{% trans "Do cz prelozeno jenom kvuli testu:) " %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

explorea/templates/accounts/verificationComplete.html
{% extends 'base.html' %}
<head>
	{% block title %}
	<title>Link invalid</title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<p>Congratulations, you can now create events. We wish you luck!</p>
	<p>
		<a href="{% url 'events:create_event' %}"><strong>Create your first event</strong></a>
	</p>
	{% endblock content %}
</body>

explorea/templates/accounts/verificationSent.html
{% extends 'base.html' %}
<head>
	{% block title %}
	<title>Email sent</title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<p>Please check your email. We have sent you email to <strong>{{ request.user.email }}</strong> with verification link. Just click on it and it is done.</p>
	<p>You can close this tab if your want</p>
	{% endblock content %}
</body>