config/urls.py
from django.conf import settings
from django.contrib import admin
from explorea.events import views
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = 	[
	path('', views.index, name='index'),
	path('events/', include('explorea.events.urls', namespace='events')),
    path('accounts/', include('explorea.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('cart/', include('explorea.cart.urls', namespace='cart')),
				]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explorea/accounts/urls.py
from . import views
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
										password_reset,
										password_reset_done,
										password_reset_confirm,
										password_reset_complete
										)

app_name = 'accounts'

urlpatterns = 	[
	path('login/', auth_views.login,{'template_name': 'accounts/login.html'}, name='login'),
	path('logout/', auth_views.logout,{'template_name': 'accounts/logged_out.html'}, name='logout'),
	path('register/', views.register, name='register'),
	path('profile/', views.profile, name='profile'),

	path('hosts/', views.host_list, name='host_list'),
	path('become-host/', views.become_host, name='become_host'),
	path('host/profile/<username>/', views.host_profile, name='host_profile'),

	path('profile/edit/', views.edit_profile, name='edit_profile'),
	path('change-password/', views.change_password, name='change_password'),
	path('reset_password/complete', password_reset_complete, name='password_reset_complete'),
	path('reset-password/done/', password_reset_done, name='password_reset_done'),
	path('reset-password/', password_reset,{'template_name': 'accounts/reset_password.html',
		'post_reset_redirect': 'password_reset_done',
		'email_template_name': 'accounts/reset_password_email.html'},
		name='reset_password'),

	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm,
		{'post_reset_redirect': 'password_reset_complete'}, name='password_reset_confirm'),
	url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.activate_host, 
		name='activate_host'),
				]

explorea/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='detail'),
    # Another possible paths ...,

				
				]

explorea/events/urls.py
from . import views
from django.urls import path

app_name = 'events'

urlpatterns = [
    path('new/', views.CreateEventView.as_view(), name='create_event'),
    path('my_events/', views.MyEventsView.as_view(), name='my_events'),
    path('search/', views.EventSearchView.as_view(), name='search'),
    
    path('detail/<slug:slug>/', views.EventDetailView.as_view(), name='event_detail'),
    path('update/<slug:slug>/', views.UpdateEventView.as_view(), name='update_event'),
    path('delete/<slug:slug>/', views.DeleteEventView.as_view(), name='delete_event'),
    
    path('<int:event_id>/new_run/', views.create_event_run, name='create_event_run'),
    path('update_run/<int:event_run_id>/', views.update_event_run,name='update_event_run'),
    path('delete_run/<int:event_run_id>/', views.delete_event_run,name='delete_event_run'),

    path('<category>/', views.EventListView.as_view(), name='events'),
                ]

explorea/cart/models.py
from django.db import models

# Create your models here.

explorea/events/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from django.db.models import Max, F, Q
from django.utils.text import slugify
# hint: these are not the django.(features) 
# better to start a whole new block
from imagekit.processors import ResizeToFill
from imagekit.models import ProcessedImageField


def thumbnail_image_url(instance, filename):
    '''upload_to for Event thumbnail image'''
    return 'user_{0}/thumb_{1}'.format(instance.host.id, filename) 


def main_image_url(instance, filename):
    '''upload_to for Event main image'''
    return 'user_{0}/main_{1}'.format(instance.host.id, filename)


def album_image_url(instance, filename):
	'''upload_to for Image model'''
	return 'user_{0}/{1}/{2}'.format(instance.album.event.host.id,
		instance.album.title, filename)


# first model = class with events
class EventQuerySet(models.QuerySet):
	'''This is a custom model that inherits all methods from models.Manager'''
	
	def filter_by_category(self, category=None):
		DbEquivalent = ''
		for shortcut in self.model.CATEGORY_CHOICES:
			if shortcut[1] == category:
				DbEquivalent = shortcut[0]
				break
		else:
			return self.all()
		
		return self.filter(category=DbEquivalent)

	
	def filter_available(self, DateFrom=None, DateTo=None, Guests=None):
		# 1. filter eventruns, 2. get IDs
		DateFrom = DateFrom or timezone.now().date()
		qs = self.annotate(max_seats=Max('eventrun__seats_available'))

		if DateTo:
			qs = EventRun.objects.filter(date__range=(DateFrom, DateTo))
		else:
			qs = EventRun.objects.filter(date__gte=DateFrom)

		if Guests:
			qs = qs.filter(seats_available__gte=Guests)

		return self.filter(pk__in=qs.values_list('event', flat=True))


class EventManager(models.Manager):

	def get_queryset(self):
		return EventQuerySet(self.model, using=self._db)

	def search(self, query=None):
		''' Our searchbar is looking in these three categories'''
		lookup = (
			Q(name__icontains=query) |
			Q(description__icontains=query) |
			Q(location__icontains=query)
				)
		return self.filter(lookup).distinct()


class EventRunQuerySet(models.QuerySet):

	def filter_by_category(self, category=None):
		DbEquivalent = ''
		for shortcut in Event.CATEGORY_CHOICES:
			if shortcut[1] == category:
				DbEquivalent = shortcut[0]
				break
		else:
			return self.all()
		return self.filter(event__category=DbEquivalent)


	def filter_available(self, DateFrom=None, DateTo=None, Guests=None):
		DateFrom = DateFrom or timezone.now().date()
		if DateTo:
			qs = self.filter(date__range=(DateFrom, DateTo))
		else:
			qs = self.filter(date__gte=DateFrom)

		if Guests:
			qs = qs.filter(seats_available__gte=Guests)
		return qs


	def FirstFilter(self, DateFrom=None, DateTo=None, Guests=None):
		qs = self.filter_available(DateFrom, DateTo, Guests).order_by('date', 'time')
		EventIds = []
		Filtered=[]

		for run in qs:
			if not run.event.id in EventIds:
				Filtered.append(run)
				EventIds.append(run.event.id)
		return Filtered


class EventRunManager(models.Manager):
	'''class based view instead of event_listing view'''

	def get_queryset(self):
		return EventRunQuerySet(self.model, using=self._db)

	def search(self, query=None):
		lookup = (
			Q(event__name__icontains=query) |
			Q(event__description__icontains=query) |
			Q(event__location__icontains=query)
				)
		return self.filter(lookup).distinct()


class Event(models.Model):
	'''Method for Event DB creation'''
	FUN 	= 'FN'
	RELAX 	= 'RX'
	EXP 	= 'EX'
	SIGHTS 	= 'SI'

	CATEGORY_CHOICES = (
		(FUN, 'fun'),
		(RELAX, 'relax'),
		(EXP, 'experience'),
		(SIGHTS, 'sights')
						)

	host		= models.ForeignKey(settings.AUTH_USER_MODEL,
									on_delete=models.CASCADE)
	name 		= models.CharField(max_length=200)
	slug 		= models.SlugField(max_length=200, unique=True, null=True)
	description = models.TextField(max_length=1000)
	location 	= models.CharField(max_length=500)
	created 	= models.DateTimeField(auto_now_add=True, null=True)
	thumbnail = ProcessedImageField(
		upload_to=thumbnail_image_url,
		processors=[ResizeToFill(300,200)],
		format='PNG',
		options={'quality':60},
		null=True)
	main_image = ProcessedImageField(
		upload_to=main_image_url,
		processors=[ResizeToFill(500,600)],
		format='PNG',
		options={'quality':100},
		null=True)
	category = models.CharField(
		max_length=20,
		choices = CATEGORY_CHOICES,
		default = FUN,
								)
	objects = EventManager()

	def __str__(self):
		return self.name

	class Meta:
		ordering 		= ['name']
		unique_together = (("name", "host"),)

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.name + '-with-' + self.host.username)
		super().save(*args, **kwargs)

		if not hasattr(self, 'album'):
			Album.objects.create(event=self)

	def ActiveRuns(self):
		today = timezone.now().date()
		return self.eventrun_set.filter(date__gte=today)

	def get_absolute_url(self):
		''' url generator'''
		return reverse('events:event_detail', args=[self.slug])


class EventRun(models.Model):
	'''Little upgrade for our first method'''
	event 			= models.ForeignKey(Event,on_delete=models.CASCADE)
	date 			= models.DateField(blank=False, null=False)
	time 			= models.TimeField(blank=False, null=False)
	seats_available = models.PositiveIntegerField(blank=False, null=False)
	price			= models.DecimalField(max_digits=10, decimal_places=2, 
											blank=False, null=False)
	objects = EventRunManager()

	def __str__(self):
		return self.event.name

	class Meta:
		ordering = ['date', 'time']



class Album(models.Model):
	'''aaaa'''
	event 	= models.OneToOneField(Event, on_delete=models.CASCADE)
	title 	= models.CharField(max_length=200, null=True)
	created = models.DateTimeField(auto_now_add=True)

	def save(self, *args, **kwargs):
		if not self.title:
			self.title = "album_" + self.event.name
		super().save(*args, **kwargs)

	def __str__(self):
		return '{}'.format(self.title)


class Image(models.Model):
	'''aaa'''
	album 	= models.ForeignKey(Album, on_delete=models.CASCADE)
	image 	= ProcessedImageField(upload_to=album_image_url,
		processors=[ResizeToFill(500,400)],
		format='PNG',
		options={'quality':80})
	title 	= models.CharField(max_length=200, null=True)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '{}/{}'.format(self.album, self.title)

	class Meta:
		ordering = ['created']

explorea/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from core.validators import validate_human_name
from .models import Profile

# global variable
UserModel = get_user_model()


class RegisterForm(UserCreationForm):
	first_name	= forms.CharField(max_length=100, validators=[validate_human_name,])
	last_name	= forms.CharField(max_length=100, validators=[validate_human_name,])

	class Meta:
		model = UserModel
		fields = [
			'username',
			'email',
			'first_name',
			'last_name',
			'password1',
			'password2',
					]

class EditUserForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    
    class Meta:
        model = UserModel
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        		]

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['about', 'avatar']


									

explorea/events/forms.py
from django import forms
from django.utils import timezone
from .models import Event, EventRun


class EventForm(forms.ModelForm):
    gallery = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), 
    	required=False)
    
    class Meta:
        model = Event
        exclude = ['host', 'slug']


class EventRunForm(forms.ModelForm):
	date = forms.DateField(input_formats=["%d.%m.%Y"], 
        widget=forms.DateInput(format = '%d.%m.%Y'))

	class Meta:
		model = EventRun
		exclude = ['event']


class EventFilterForm(forms.Form):
	'''This widget will help us to find our events'''
	DateFrom 	= forms.DateField(label="from", initial=None,
			widget=forms.SelectDateWidget, required=False)
	DateTo 		= forms.DateField(label="to", initial=None,
			widget=forms.SelectDateWidget, required=False)
	Guests 		= forms.IntegerField(required=False, min_value=1)

	def clean(self):
		super().clean()
		DateFrom 	= self.cleaned_data.get('DateFrom')
		DateTo 		= self.cleaned_data.get('DateTo')
		if ((DateFrom and DateTo) and DateFrom > DateTo):
			self.add_error('DateFrom', 'Your selected date is later than date to')

		for name, date in [('DateFrom', DateFrom), ('DateTo', DateTo)]:
			if date and date < timezone.now().date():
				self.add_error(name, 'You have selected date in the past')


class EventSearchFilterForm(EventFilterForm):
    
     q = forms.CharField(required=False, max_length=1000, initial='',
                                    widget=forms.HiddenInput())

explorea/accounts/views.py
# imports lower are important in the "become_host" view 
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import PasswordResetTokenGenerator
# aaa
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
# a
from .models import Profile
# b
from .forms import RegisterForm, EditProfileForm, EditUserForm


token_generator = PasswordResetTokenGenerator()
UserModel = get_user_model()


@login_required
def profile(request):
	''' This function render only basic information about the user's account '''
	return render(request, 'accounts/profile.html')


def register(request):
	''' The register function. '''
	if request.method == 'POST':
		# Create thte form and populate it with data from the POST request
		form = RegisterForm(request.POST)

		# Validate the data in the form
		if form.is_valid():
			user = form.save()
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=user.username, password=raw_password)
			login(request, user)
			return redirect('profile')
	# if the request method is GET type
	form = RegisterForm()
	return render(request, 'accounts/register.html', {'form': form})


@login_required
def edit_profile(request):
	''' we want to edit our profile section '''
	UserForm = EditUserForm(request.POST or None, instance=request.user)
	ProfileForm = EditProfileForm(request.POST or None, request.FILES or None,
		instance=request.user.profile)

	if request.method == 'POST':
		if UserForm.is_valid() and ProfileForm.is_valid():
			user = UserForm.save()
			profile = ProfileForm.save()

			return redirect('accounts:profile')
	return render(request, 'accounts/edit_profile.html',
		{'UserForm': UserForm, 'ProfileForm': ProfileForm})


@login_required
def change_password(request):
	''' The user wants to change his current password'''

	if not request.user.is_authenticated:
		return redirect('login')

	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)
		
		if form.is_valid():
			user = form.save()
			# we need to obtain a new session hash due to new password
			update_session_auth_hash(request, user)
			return redirect('accounts/profile/')
		else:
			return render(request, 'accounts/change_password.html', {'form': form})
	
	# GET method
	else:
		form = PasswordChangeForm(user=request.user)
		return render(request, 'accounts/change_password.html', {'form': form})


@login_required
def host_list(request):
	''' This view is accessible only to those registerred at our site.'''
	profiles = Profile.objects.filter(is_host=True)
	if request.user.profile.is_host:
		profiles = profiles.exclude(user__pk=request.user.id)

	return render(request, 'accounts/host_list.html', {'profiles':profiles})


@login_required
def become_host(request):
	''' aaa '''
	verificationEmailTemplate = 'accounts/hostVerificationEmail.html'
	emailContext = {
		'user': request.user,
		'domain': get_current_site(request).domain,
		'uidb64': urlsafe_base64_encode(force_bytes(request.user.pk)).decode(),
		'token': token_generator.make_token(request.user)
					}
	html_body 	= render_to_string(verificationEmailTemplate, emailContext)
	subject 	= 'Explorea Host Verification'
	from_email 	= 'admin@explorea.com'
	to_email 	= request.user.email
	email 		= EmailMessage(subject, html_body, from_email, [to_email])
	email.send()

	return render(request, 'accounts/verificationSent.html')


def activate_host(request, uidb64, token):
	'''We want to render html correctly with proper urls.'''
	try:
		uid 	= urlsafe_base64_decode(uidb64).decode()
		user 	= UserModel._default_manager.get(pk=uid)
	except (TypeError, ValueError, OverflowError, User.DoesNotExist):
		user 	= None

	if user is not None and token_generator.check_token(user, token):
		user.profile.is_host = True
		user.profile.save()
		return render(request, 'accounts/verificationComplete.html')
	else:
		return render(request, 'accounts/invalidLink.html')


@login_required
def host_profile(request, username):
    host = UserModel.objects.get(username=username)
    return render(request, 'accounts/hostProfile.html', {'host': host})

explorea/cart/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Our first view for testing purposes
# ...
class CartDetailView(TemplateView):
    template_name = "cart/cart_detail.html"

explorea/templates/events/create_event.html
{% extends 'base.html '%}
<html>
<head>
	{% block title %}
	<title> Events </title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<div>
		<h2>Edit event {{ event.name }}</h2>
		<form method="post" enctype="multipart/form-data">
	    	{% csrf_token %}
	    	{% for field in form.visible_fields %}
			    <p>{{ field.label_tag}}{{ field }}</p>
			    {% for error in field.errors %}
			    	{{ error }}
			    {% endfor %}      
		    {% endfor %}
			<button type="submit">Save</button>
		</form>
	</div>
{% endblock content %}
</body>
</html>

explorea/templates/events/create_event_run.html
{% extends "base.html" %}
<html>
<head>
	{% block title %}
	<title>Create Event run</title>
	{% endblock title%}
</head>
<body>
{% block content %}
	<h2>New Run</h2>
	<form method='POST'>
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="Save">
	</form>
{% endblock content %}
</body>
</html>

explorea/templates/events/event_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<br>
    <p>Do you want to delete "{{ object }}"?</p>
    <br>
    <button type="submit">Delete</button>
    <a class="FilterButton" href="{{ object.get_absolute_url }}">Cancel</a>
</form>
{% endblock %}

explorea/templates/events/event_detail.html
{% extends 'base.html' %}
{% load EventTags %}
<html>
<head>
	{% block title %}
	<title> Details about the event </title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<div class="container">
		<br>
		<h2>{{ event.name }} 
		    | <a href="{% url 'events:update_event' event.slug %}">UPDATE</a> 
		    | <a href="{% url 'events:delete_event' event.slug %}">DELETE</a>
		</h2>
		<br>
		<ul class="list-group">
			<li class="list-group-item">Username: {{ event.host }}</li>
			<li class="list-group-item">Location: {{ event.location }}</li>
			<li class="list-group-item">Category: {{ event.category }}</li>
			<li class="list-group-item">Description: {{ event.description }}</li>
		</ul>
		<br>
		<div class="main_image">
    		{% if event|has:'main_image' %}
    			<img src="{{ event.main_image.url }}">
    		{% else %}
    			<div class="NotAvailable"></div>
    		{% endif %}
		</div>
		<p>{{ event.description }}</p>
		<br>
		<!--Image slideshow-->
		<div class="OwlCarousel">
		{% for image in event.album.image_set.all %}
		<img src="{{ image.image.url }}" alt="{{ image.title }}">
		{% endfor %}
		</div>
		<br>
		<h2>Availability</h2>
		<table>
			<tr>
			    <th>DATE</th>
			    <th>SEATS</th>
			    <th>PRICE</th>
			</tr>
			<tr>
			{% for run in runs %}
				<td>{{ run.date }}, {{ run.time }}</td>
				<td>{{ run.seats_available }}</td>
				<td>{{ run.price }}</td>
			</tr>	
				<td><a href="{% url 'events:update_event_run' event.slug %}"">CHANGE</a></td>
				<td><a href="/events/deleteRun/{{ run.id }}">DELETE</a></td>
 			</tr>
			{% endfor %}
		</table>
		<br>
		<a href='/events/my_events'>Back</a> | <a href='/events/{{ event.id }}/new_run/'>Add new Run</a>
	</div>
	{% endblock content %}
</body>
</html>

explorea/templates/events/event_listing.html
{% extends 'base.html' %}
{% load EventTags %}}
<html>
<head>
	{% block title %}
	<title> List of events </title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<div class="FilterBanner">
		<h1>Let's take a look around</h1>		
	</div>

	<form class="EventFilters" action={{ request.get_full_path }} method="GET">
		{% for hidden_field in form.hidden_fields %}
			{{ hidden_field }}
		{% endfor %}
		
		{# <input type="hidden" name='q'  value="{% if 'q' in request.GET %}"
		{{ request.GET.q }} {% endif %}> #}

    	{% for field in FilterForm.visible_fields %}
    		<div class="FormFilter">
    			{{ field.label_tag }} {{ field }}
    				<div class="errors">
	        	    	{% for error in field.errors %}
	            		<div class="error">
	            			{{ error }}
	            		</div>
	                	{% endfor %}
	            	</div>
        	</div>
        {% endfor %}
    	<button type="submit">Filter</button>
	</form>
	
	<div class="FilterButtonGroup">
		<a class="FilterButton" href="{% url 'events:events' 'all' %}">All Events</a>
		<a class="FilterButton" href="{% url 'events:events' 'fun' %}">Fun</a>
    	<a class="FilterButton" href="{% url 'events:events' 'experience' %}">Experience</a>
    	<a class="FilterButton" href="{% url 'events:events' 'sights' %}">Sights</a>
    	<a class="FilterButton" href="{% url 'events:events' 'relax' %}">Relax</a>
	</div>

	<div class="LowerContainer">
		{% if EventRuns %}
		<div class="LowerTable">
			{% for EventRun in EventRuns %}
			<a class="EventTable" href="{{ EventRun.event.get_absolute_url }}">
				{% if EventRun.event|has:'thumbnail' %}
					<img src="{{ EventRun.event.thumbnail.url }}">
				{% else %}
				<div class="NotAvailable"></div>
				{% endif %}
				<div class="EventDetails">
					<p>{{ EventRun.event.host }}</p>
					<p>{{ EventRun.event.name }}</p>
					<p>{{ EventRun.event.location }}</p>
					<p><strong>Start:</strong> {{ EventRun.date }}</p>
    				<p><strong>Price:</strong> {{ EventRun.event.eventrun_set.all|active|min_attr_value:"price" }}</p>
    				<p><strong>Seats:</strong> {{ EventRun.seats_available }} </p>
				</div>
			</a>
			{% endfor %}
		{% else %}
			<div class="info empty-search">No events found ...</div>
    	{% endif %}
    	</div>
    </div>
    {% include 'pagination.html' with page=page_obj %}
    {% endblock content %}
	
</body>
</html>

explorea/templates/events/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
	{% block title%}
	<title>Main page</title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<div class="main-banner">
	    <p class="claim">Welcome aboard!</p>
		    <a href="{% url 'events:events' 'fun' %}">Fun</a>
		    <a href="{% url 'events:events' 'experience' %}">Experience</a>
		    <a href="{% url 'events:events' 'sights' %}">Sights</a>
		    <a href="{% url 'events:events' 'relax' %}">Relax</a>
	</div>
	{% endblock content %}
</body>
</html>

explorea/templates/events/my_events.html
{% extends 'base.html' %}
<html>
<head>
	{% block title %}
	<title>My events</title>
	{% endblock title %}
</head>
<body>
	{% block content %}
	<div class="container">
		<br>
		<h2>My events</h2>
		<a class="btn btn-outline-primary" data-toggle="collapse" href="/events/new/" role="button" aria-expanded="false" aria-controls="collapseExample">Add your Event</a><br>
		<br>
		<table style='text-align: left;'>
			<tr>
				<th style="
					background-color: DodgerBlue;
					color: white;
					font-size: 15px;
					">Name
				</th>
				<th style="
					background-color: DodgerBlue;
					color: white;
					font-size: 15px;
					">Location
				</th>
				<!-- Jenom abych srovnal hlavicku s nasledujicimi radky -->
				<th style="
					background-color: DodgerBlue;
					color: white;
					font-size: 15px;
					">
				</th>
				<th style="
					background-color: DodgerBlue;
					color: white;
					font-size: 15px;
					">
				</th>
			</tr>
			{% for event in events %}
			<tr>
				<td><a href="{% url 'events:event_detail' event.slug %}">{{ event.name }}</a></td>
				<td>{{ event.location }}</td>
				<td><a href="{% url 'events:update_event' event.slug %}">Update</a> </td>
				<td><a href="{% url 'events:delete_event' event.slug %}">Delete</a></td>
			</tr>
			{% endfor %}
		</table>
	</div>
	{% endblock content %}
</body>
</html>

explorea/templates/events/update_event_run.html
{% extends "base.html" %}
<html>
<head>
	{% block title %}
	<title>Update event run</title>
	{% endblock title %}}
</head>
<body>
	{% block content %}
	<div class="container">
	<h2>{{ form.instance.event.name }}</h2>

	<form method='POST'>
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="Save">
	</form>
	</div>
	{% endblock content %}
</body>
</html>